### ISSUE TITLE
Support graphql-config for schema configuration

### ISSUE THREAD

**Issue by schickling** [relayjs/eslint-plugin-relay#4]
Thanks so much for creating this awesome project and improving workflows when working with Relay.

To make the configuration a bit easier, we've created [graphql-config](https://github.com/graphcool/graphql-config). It would be great if this tool would support this standard as well!

**Comment by pranaygp** [comment]
@schickling Thanks for taking an interest in this project :)

Do you have any ideas on how we could use graphqlconfig for this plugin?

**Comment by kassens** [comment]
For now, this project is independent of any schema. This is by design as it ensures the linting is fast and easy on memory even for large schemas.

We have to see if we eventually want to integrate with https://github.com/graphql/graphql-language-service which provides schema aware editor support using a persistent demon.
